OUTPUT: "./output"
DATASET:
  root_dataset: "/home/haiwen/Datasets/VOC2012"
  num_class: 21
  image_size: (256, 256)
  crop_size: (224, 224)
  segm_downsampling_rate: 16
  batch_size: 32

MODEL:
  fc_dim: 2048

TRAIN:
  num_epochs: 100
  start_epoch: 0
  optim: "SGD"
  base_lr: 0.01
  momentum: 0.9
  weight_decay: 1e-4
  lr_min: 5e-6
  warmup_lr: 5e-7
  warmup_steps: 30
  early_stop: 10
  resume: False
  mnt_mode: max
  workers: 4
  seed: 304

LOG:
  dir_name: "log"
  train_file: "train.log"
  tensorboard_file: "tensorborad"


VALID:
  dir: "valid"